server:
  port: 8002
spring:
  application:
    name: reptile-task
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: task8002

logging:
  level:
    com.offcn.reptile.service: debug