server:
  port: 80

spring:
  application:
    name: reptile-web
  mvc:
    view:
      suffix: .html
      prefix: page/

  redis:
    port: 6379
    host: 127.0.0.1

  datasource:
    url: jdbc:mysql://192.168.190.50:3306/reptile?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    solr:
      host: http://localhost:9900/solr
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: web80
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.offcn.reptile.domain
